# Generated by Django 3.0.2 on 2021-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='score',
            field=models.FloatField(),
        ),
    ]
